server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/melon?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

mybatis:
  configuration:
    map-underscore-to-camel-case: true


secret: monster
expire_time: 5

#jwt:
#  secret: monster
#  expire_time: 5