server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/melon?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.sina.com
    username: monster_zzz@sina.com
    password: a885471db6e6302a
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 60s
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-wait: -1
        max-active: -1
  rabbitmq:
    host: 127.0.01
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
#    listener:
#      simple:
#        concurrency: 1
#        max-concurrency: 1



mail_form_addr: monster_zzz@sina.com


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml
  typeAliasesPackage: com.monster.melon.pojo


secret: monster
expire_time: 30
comment_page: 7
event_num: 7
news_page: 7


endpoint: http://oss-cn-beijing.aliyuncs.com
accessKeyId: LTAI4Fn1Vutg5RhfQkaVgHXn
accessKeySecret: *****
bucketName: melon-site


logging:
  level:
    com.monster.mapper: debug
